; PARALLEL.ASM - Parallel rendering procedure
; Assemble: ml64 /c parallel.asm

INCLUDE .\include\structs.inc
INCLUDE .\include\externs.inc

.CODE

PUBLIC PARALLELRENDERTOSCREEN

PARALLELRENDERTOSCREEN PROC
    XOR RCX, RCX
    LEA R11, UPSCALEDROW
ROWRENDERLOOP:
    MOV AL, BYTE PTR [R11 + RCX]
    CMP AL, 00H
    JNZ NEXTRENDERROWCHECK
    INC BYTE PTR [R11 + RCX]
    
    MOV RDX, RCX
    SHL RDX, 0EH
    ADD RDX, [UPSCALEDBUFFER]
    
    MOV R9, RCX
    SHL R9, 0AH
    LEA R10, OUTPUTFBUFFER
    ADD R9, R10
    
    XOR R8, R8
    XOR R10, R10
    XOR RAX, RAX
RENDERFIRSTROW:
    MOV EAX, DWORD PTR [R9]
    MOV DWORD PTR [RDX + R10], EAX
    ADD R10, 04H
    
    TEST R8, 03H
    JNZ NOTNEXTPIXELYET
    ADD R9, 04H
NOTNEXTPIXELYET:
    INC R8
    CMP R8, 0400H
    JNZ RENDERFIRSTROW
    
    XOR R8, R8
    XOR R9, R9
    XOR RAX, RAX
COPYFIRSTROWTOTHREEOTHERS:
    MOV RAX, QWORD PTR [RDX + R8]
    MOV QWORD PTR [RDX + R8 + 1000H], RAX
    MOV QWORD PTR [RDX + R8 + 2000H], RAX
    MOV QWORD PTR [RDX + R8 + 3000H], RAX
    ADD R8, 08H
    INC R9
    CMP R9, 0200H
    JNZ COPYFIRSTROWTOTHREEOTHERS
    
    INC UPSCALEDCOUNT
NEXTRENDERROWCHECK:
    INC RCX
    CMP RCX, 0100H
    JNZ ROWRENDERLOOP
    
    RET
PARALLELRENDERTOSCREEN ENDP

END
